### ISSUE TITLE
Compilation Error: "class file for org.springframework.core.env.EnvironmentCapable not found"

### ISSUE THREAD

**Issue by keheliya** [jbarrez/Activiti-KickStart#1]
I'm getting the following error when building the source using mvn clean install -rf :activiti-kickstart-ui

[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /data/dev/activti/jbarrez/Activiti-KickStart/activiti-kickstart-ui/src/main/java/org/activiti/kickstart/KickstartApplicationServlet.java:[48,44] cannot access org.springframework.core.env.EnvironmentCapable
class file for org.springframework.core.env.EnvironmentCapable not found
        return (Application) applicationContext.getBean(KickstartApplication.class);
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.360s
[INFO] Finished at: Wed Jan 30 11:57:40 IST 2013
[INFO] Final Memory: 13M/490M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project activiti-kickstart-ui: Compilation failure
[ERROR] /data/dev/activti/jbarrez/Activiti-KickStart/activiti-kickstart-ui/src/main/java/org/activiti/kickstart/KickstartApplicationServlet.java:[48,44] cannot access org.springframework.core.env.EnvironmentCapable
[ERROR] class file for org.springframework.core.env.EnvironmentCapable not found
[ERROR] return (Application) applicationContext.getBean(KickstartApplication.class);
[ERROR] -> [Help 1]

**Comment by keheliya** [comment]
I think this issue is also reported here..
http://forums.activiti.org/en/viewtopic.php?t=4914&p=20426

**Comment by giangkt** [comment]
Hi there! Is there any fix on this bug? I can not compile the UI package also.

This is so great tool using for modeling stage. Something like IBM blueworkslive :)

Hope you keep your support us on this.

Thanks. Giang.

**Comment by giangkt** [comment]
I got the solution. Just change the spring core version:
<dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>3.1.0.M2</version>
        </dependency>

Thanks.

**Comment by giangkt** [comment]
Another error when deploy the ui war in Tomcat 7:
Any idea on this?

SEVERE: Error deploying web application archive D:\Java\tomcat\webapps\activiti-
kickstart-ui-1.1.war
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catal
ina.LifecycleException: Failed to start component [StandardEngine[Catalina].Stan
dardHost[localhost].StandardContext[/activiti-kickstart-ui-1.1]]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase
.java:904)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:87
7)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)

```
    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:977)

    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:
```

1655)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:44
1)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExec
utor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:908)
        at java.lang.Thread.run(Thread.java:662)
Mar 22, 2013 9:34:14 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory D:\Java\tomcat\webapps\docs
Mar 22, 2013 9:34:14 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory D:\Java\tomcat\webapps\examples
Mar 22, 2013 9:34:14 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory D:\Java\tomcat\webapps\host-manager
Mar 22, 2013 9:34:14 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory D:\Java\tomcat\webapps\manager
Mar 22, 2013 9:34:15 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory D:\Java\tomcat\webapps\ow
log4j:WARN No appenders could be found for logger (owd.core).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more in
fo.
Mar 22, 2013 9:34:17 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory D:\Java\tomcat\webapps\ROOT
Mar 22, 2013 9:34:17 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8090"]
Mar 22, 2013 9:34:17 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-8029"]
Mar 22, 2013 9:34:17 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 6118 ms

**Comment by jbarrez** [comment]
Hi guys,

This project has been moved to the Activiti code base (again), see https://github.com/Activiti/Activiti/tree/master/modules/activiti-simple-workflow

The UI is also part of Activiti Explorer.

Although it is not yet up to the same level as this project (eg the rest API is not yet finished), it will be in the near future. So at that point, this project will probably be closed down.
