### ISSUE TITLE
CMIS re-deployment is not working as expected

### ISSUE THREAD

**Issue by ardamose123** [jbarrez/Activiti-KickStart#7]
The CMIS deployment is not working correctly when you try to do a re-deployment about the model. This throws an exception:

<pre> 
java.io.IOException: Error while checking in new version of model
at org.activiti.designer.kickstart.eclipse.navigator.CmisUtil.uploadModel(CmisUtil.java:186)
at org.activiti.designer.kickstart.eclipse.ui.wizard.diagram.ExportKickstartProcessWizard.exportProcess(ExportKickstartProcessWizard.java:188)
at org.activiti.designer.kickstart.eclipse.ui.wizard.diagram.ExportKickstartProcessWizard$1.run(ExportKickstartProcessWizard.java:88)
at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
Caused by: org.apache.chemistry.opencmis.commons.exceptions.CmisRuntimeException: Internal Server Error
at org.apache.chemistry.opencmis.client.bindings.spi.atompub.AbstractAtomPubService.convertStatusCode(AbstractAtomPubService.java:487)
at org.apache.chemistry.opencmis.client.bindings.spi.atompub.AbstractAtomPubService.put(AbstractAtomPubService.java:653)
at org.apache.chemistry.opencmis.client.bindings.spi.atompub.AbstractAtomPubService.put(AbstractAtomPubService.java:640)
at org.apache.chemistry.opencmis.client.bindings.spi.atompub.VersioningServiceImpl.checkIn(VersioningServiceImpl.java:164)
at org.apache.chemistry.opencmis.client.runtime.DocumentImpl.checkIn(DocumentImpl.java:274)
at org.apache.chemistry.opencmis.client.runtime.DocumentImpl.checkIn(DocumentImpl.java:528)
at org.activiti.designer.kickstart.eclipse.navigator.CmisUtil.uploadModel(CmisUtil.java:183)
... 3 more"
</pre>

Our environment is:
- Ubuntu 14.04
- Eclipse Version: 3.8.1 and Build id: debbuild
- Plugin Activiti BPMN 2.0 designer - http://activiti.org/designer/update/
- Alfresco One version 4.2.1

**Comment by ardamose123** [comment]
No solution provided.
